name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
