name: publish_npm_package

on:
  push:
    branches:
      - main
    tags: ['v*']

jobs:
  publish:
    name: 'Publish npm package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          tag_name: 'v%s'
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@notainc'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create release on GitHub
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="Release $tag" \
            --draft \
            --generate-notes
